version: '3.5'
services:
  flame:
    image: pawelmalak/flame
    container_name: flame
    volumes:
      - '/home/arsen/docker:/var/run/docker.sock'
    ports:
      - '5005:5005'
    environment:
      - 'PASSWORD=12345'
    restart: unless-stopped